import type { Product, Brand } from './types'

export const brands: Brand[] = [
  {
    id: 'mg',
    name: 'MG',
    nameAr: 'إم جي',
    logo: '/brands/mg.svg',
    models: ['MG 5', 'MG 6', 'MG ZS', 'MG HS', 'MG RX5', 'MG RX8'],
  },
  {
    id: 'chery',
    name: 'Chery',
    nameAr: 'شيري',
    logo: '/brands/chery.svg',
    models: ['Tiggo 2', 'Tiggo 3', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5'],
  },
  {
    id: 'geely',
    name: 'Geely',
    nameAr: 'جيلي',
    logo: '/brands/geely.svg',
    models: ['Emgrand', 'Coolray', 'Azkarra', 'Okavango', 'Monjaro'],
  },
]

export const categories = [
  { id: 'engine', name: 'Engine Parts', nameAr: 'قطع المحرك' },
  { id: 'brakes', name: 'Brakes', nameAr: 'الفرامل' },
  { id: 'suspension', name: 'Suspension', nameAr: 'نظام التعليق' },
  { id: 'electrical', name: 'Electrical', nameAr: 'الكهرباء' },
  { id: 'body', name: 'Body Parts', nameAr: 'قطع الهيكل' },
  { id: 'filters', name: 'Filters', nameAr: 'الفلاتر' },
  { id: 'oils', name: 'Oils & Fluids', nameAr: 'الزيوت والسوائل' },
  { id: 'accessories', name: 'Accessories', nameAr: 'الإكسسوارات' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Air Filter - MG ZS',
    nameAr: 'فلتر هواء - إم جي زد إس',
    brand: 'MG',
    category: 'filters',
    categoryAr: 'الفلاتر',
    price: 85,
    originalPrice: 120,
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 124,
    inStock: true,
    partNumber: 'MG-AF-ZS-001',
    description: 'High-quality air filter for MG ZS models. Ensures optimal engine performance.',
    descriptionAr: 'فلتر هواء عالي الجودة لموديلات إم جي زد إس. يضمن أداء محرك مثالي.',
  },
  {
    id: '2',
    name: 'Brake Pads Set - Chery Tiggo 7',
    nameAr: 'طقم فحمات فرامل - شيري تيجو 7',
    brand: 'Chery',
    category: 'brakes',
    categoryAr: 'الفرامل',
    price: 220,
    originalPrice: 280,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 89,
    inStock: true,
    partNumber: 'CH-BP-T7-002',
    description: 'Premium ceramic brake pads for Chery Tiggo 7. Superior stopping power.',
    descriptionAr: 'فحمات فرامل سيراميك ممتازة لشيري تيجو 7. قوة توقف فائقة.',
  },
  {
    id: '3',
    name: 'Oil Filter - Geely Coolray',
    nameAr: 'فلتر زيت - جيلي كولراي',
    brand: 'Geely',
    category: 'filters',
    categoryAr: 'الفلاتر',
    price: 45,
    image: 'https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    partNumber: 'GL-OF-CR-003',
    description: 'Genuine oil filter for Geely Coolray. Maintains engine cleanliness.',
    descriptionAr: 'فلتر زيت أصلي لجيلي كولراي. يحافظ على نظافة المحرك.',
  },
  {
    id: '4',
    name: 'Shock Absorber Front - MG HS',
    nameAr: 'ممتص صدمات أمامي - إم جي إتش إس',
    brand: 'MG',
    category: 'suspension',
    categoryAr: 'نظام التعليق',
    price: 450,
    originalPrice: 550,
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 67,
    inStock: true,
    partNumber: 'MG-SA-HS-004',
    description: 'High-performance front shock absorber for MG HS. Smooth ride guaranteed.',
    descriptionAr: 'ممتص صدمات أمامي عالي الأداء لإم جي إتش إس. قيادة سلسة مضمونة.',
  },
  {
    id: '5',
    name: 'Headlight Assembly - Chery Tiggo 8',
    nameAr: 'مجموعة مصابيح أمامية - شيري تيجو 8',
    brand: 'Chery',
    category: 'electrical',
    categoryAr: 'الكهرباء',
    price: 680,
    image: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 45,
    inStock: true,
    partNumber: 'CH-HL-T8-005',
    description: 'OEM quality headlight assembly for Chery Tiggo 8. LED included.',
    descriptionAr: 'مجموعة مصابيح أمامية بجودة OEM لشيري تيجو 8. تشمل LED.',
  },
  {
    id: '6',
    name: 'Engine Oil 5W-30 Full Synthetic',
    nameAr: 'زيت محرك 5W-30 صناعي بالكامل',
    brand: 'MG',
    category: 'oils',
    categoryAr: 'الزيوت والسوائل',
    price: 120,
    originalPrice: 150,
    image: 'https://images.unsplash.com/photo-1635784033736-2c4f22ffd60b?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 234,
    inStock: true,
    partNumber: 'OIL-5W30-FS-006',
    description: 'Premium full synthetic engine oil. Suitable for all Chinese car brands.',
    descriptionAr: 'زيت محرك صناعي ممتاز بالكامل. مناسب لجميع السيارات الصينية.',
  },
  {
    id: '7',
    name: 'Timing Belt Kit - Geely Emgrand',
    nameAr: 'طقم سير توقيت - جيلي إمجراند',
    brand: 'Geely',
    category: 'engine',
    categoryAr: 'قطع المحرك',
    price: 380,
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 78,
    inStock: false,
    partNumber: 'GL-TB-EM-007',
    description: 'Complete timing belt kit for Geely Emgrand. Includes tensioner and pulley.',
    descriptionAr: 'طقم سير توقيت كامل لجيلي إمجراند. يشمل الشداد والبكرة.',
  },
  {
    id: '8',
    name: 'Side Mirror - MG 5',
    nameAr: 'مرآة جانبية - إم جي 5',
    brand: 'MG',
    category: 'body',
    categoryAr: 'قطع الهيكل',
    price: 195,
    originalPrice: 240,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 56,
    inStock: true,
    partNumber: 'MG-SM-M5-008',
    description: 'Electric side mirror with heating function for MG 5.',
    descriptionAr: 'مرآة جانبية كهربائية مع وظيفة التسخين لإم جي 5.',
  },
  {
    id: '9',
    name: 'Cabin Air Filter - Chery Arrizo 5',
    nameAr: 'فلتر مكيف - شيري أريزو 5',
    brand: 'Chery',
    category: 'filters',
    categoryAr: 'الفلاتر',
    price: 55,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 112,
    inStock: true,
    partNumber: 'CH-CAF-A5-009',
    description: 'Activated carbon cabin filter for Chery Arrizo 5. Fresh air guaranteed.',
    descriptionAr: 'فلتر مكيف بالكربون النشط لشيري أريزو 5. هواء نقي مضمون.',
  },
  {
    id: '10',
    name: 'Radiator - Geely Azkarra',
    nameAr: 'رادياتير - جيلي أزكارا',
    brand: 'Geely',
    category: 'engine',
    categoryAr: 'قطع المحرك',
    price: 520,
    originalPrice: 650,
    image: 'https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 34,
    inStock: true,
    partNumber: 'GL-RAD-AZ-010',
    description: 'High-efficiency aluminum radiator for Geely Azkarra. Superior cooling.',
    descriptionAr: 'رادياتير ألومنيوم عالي الكفاءة لجيلي أزكارا. تبريد فائق.',
  },
  {
    id: '11',
    name: 'Spark Plugs Set - MG 6',
    nameAr: 'طقم شمعات إشعال - إم جي 6',
    brand: 'MG',
    category: 'engine',
    categoryAr: 'قطع المحرك',
    price: 140,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 189,
    inStock: true,
    partNumber: 'MG-SP-M6-011',
    description: 'Iridium spark plugs set for MG 6. Enhanced ignition performance.',
    descriptionAr: 'طقم شمعات إشعال إيريديوم لإم جي 6. أداء إشعال محسن.',
  },
  {
    id: '12',
    name: 'Wheel Bearing - Chery Tiggo 4',
    nameAr: 'رمان بلي عجل - شيري تيجو 4',
    brand: 'Chery',
    category: 'suspension',
    categoryAr: 'نظام التعليق',
    price: 165,
    originalPrice: 200,
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 67,
    inStock: true,
    partNumber: 'CH-WB-T4-012',
    description: 'Premium wheel bearing for Chery Tiggo 4. Smooth rotation guaranteed.',
    descriptionAr: 'رمان بلي عجل ممتاز لشيري تيجو 4. دوران سلس مضمون.',
  },
]
